interval-seconds: 10
kick-ip-message: The last logged-in sub player was kicked because the player was full. (UUID duplication)
kick-uuid-message: The last logged-in sub player was kicked because the player was full. (IP address duplication)
